spring:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:file:/data/demo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  banner:
    location: classpath:springboot-logo.txt
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
huhoot:
  socket:
    port: '8082'
  serverip: 0.0.0.0
  secret-key: huhootsecretkey
server:
  port: '8080'
